package weixin.assistant.model;

public class VipBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.weixin_gzh_id
     *
     * @mbggenerated
     */
    private Integer weixinGzhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_business.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    public VipBusiness(Integer id, Integer weixinGzhId, String name, String tel, String addr, String account, String city) {
        this.id = id;
        this.weixinGzhId = weixinGzhId;
        this.name = name;
        this.tel = tel;
        this.addr = addr;
        this.account = account;
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    public VipBusiness() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.id
     *
     * @return the value of vip_business.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.id
     *
     * @param id the value for vip_business.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.weixin_gzh_id
     *
     * @return the value of vip_business.weixin_gzh_id
     *
     * @mbggenerated
     */
    public Integer getWeixinGzhId() {
        return weixinGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.weixin_gzh_id
     *
     * @param weixinGzhId the value for vip_business.weixin_gzh_id
     *
     * @mbggenerated
     */
    public void setWeixinGzhId(Integer weixinGzhId) {
        this.weixinGzhId = weixinGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.name
     *
     * @return the value of vip_business.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.name
     *
     * @param name the value for vip_business.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.tel
     *
     * @return the value of vip_business.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.tel
     *
     * @param tel the value for vip_business.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.addr
     *
     * @return the value of vip_business.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.addr
     *
     * @param addr the value for vip_business.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.account
     *
     * @return the value of vip_business.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.account
     *
     * @param account the value for vip_business.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_business.city
     *
     * @return the value of vip_business.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_business.city
     *
     * @param city the value for vip_business.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}