package weixin.xigua.model;

import java.util.Date;

public class WpwxSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.trigger_time
     *
     * @mbggenerated
     */
    private Date triggerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.trigger_user
     *
     * @mbggenerated
     */
    private String triggerUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.trigger_public
     *
     * @mbggenerated
     */
    private String triggerPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para1
     *
     * @mbggenerated
     */
    private String para1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para2
     *
     * @mbggenerated
     */
    private String para2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para3
     *
     * @mbggenerated
     */
    private String para3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para4
     *
     * @mbggenerated
     */
    private String para4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para5
     *
     * @mbggenerated
     */
    private String para5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.para6
     *
     * @mbggenerated
     */
    private String para6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_schedule.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.id
     *
     * @return the value of wpwx_schedule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.id
     *
     * @param id the value for wpwx_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.type
     *
     * @return the value of wpwx_schedule.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.type
     *
     * @param type the value for wpwx_schedule.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.trigger_time
     *
     * @return the value of wpwx_schedule.trigger_time
     *
     * @mbggenerated
     */
    public Date getTriggerTime() {
        return triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.trigger_time
     *
     * @param triggerTime the value for wpwx_schedule.trigger_time
     *
     * @mbggenerated
     */
    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.trigger_user
     *
     * @return the value of wpwx_schedule.trigger_user
     *
     * @mbggenerated
     */
    public String getTriggerUser() {
        return triggerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.trigger_user
     *
     * @param triggerUser the value for wpwx_schedule.trigger_user
     *
     * @mbggenerated
     */
    public void setTriggerUser(String triggerUser) {
        this.triggerUser = triggerUser == null ? null : triggerUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.trigger_public
     *
     * @return the value of wpwx_schedule.trigger_public
     *
     * @mbggenerated
     */
    public String getTriggerPublic() {
        return triggerPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.trigger_public
     *
     * @param triggerPublic the value for wpwx_schedule.trigger_public
     *
     * @mbggenerated
     */
    public void setTriggerPublic(String triggerPublic) {
        this.triggerPublic = triggerPublic == null ? null : triggerPublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para1
     *
     * @return the value of wpwx_schedule.para1
     *
     * @mbggenerated
     */
    public String getPara1() {
        return para1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para1
     *
     * @param para1 the value for wpwx_schedule.para1
     *
     * @mbggenerated
     */
    public void setPara1(String para1) {
        this.para1 = para1 == null ? null : para1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para2
     *
     * @return the value of wpwx_schedule.para2
     *
     * @mbggenerated
     */
    public String getPara2() {
        return para2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para2
     *
     * @param para2 the value for wpwx_schedule.para2
     *
     * @mbggenerated
     */
    public void setPara2(String para2) {
        this.para2 = para2 == null ? null : para2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para3
     *
     * @return the value of wpwx_schedule.para3
     *
     * @mbggenerated
     */
    public String getPara3() {
        return para3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para3
     *
     * @param para3 the value for wpwx_schedule.para3
     *
     * @mbggenerated
     */
    public void setPara3(String para3) {
        this.para3 = para3 == null ? null : para3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para4
     *
     * @return the value of wpwx_schedule.para4
     *
     * @mbggenerated
     */
    public String getPara4() {
        return para4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para4
     *
     * @param para4 the value for wpwx_schedule.para4
     *
     * @mbggenerated
     */
    public void setPara4(String para4) {
        this.para4 = para4 == null ? null : para4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para5
     *
     * @return the value of wpwx_schedule.para5
     *
     * @mbggenerated
     */
    public String getPara5() {
        return para5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para5
     *
     * @param para5 the value for wpwx_schedule.para5
     *
     * @mbggenerated
     */
    public void setPara5(String para5) {
        this.para5 = para5 == null ? null : para5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.para6
     *
     * @return the value of wpwx_schedule.para6
     *
     * @mbggenerated
     */
    public String getPara6() {
        return para6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.para6
     *
     * @param para6 the value for wpwx_schedule.para6
     *
     * @mbggenerated
     */
    public void setPara6(String para6) {
        this.para6 = para6 == null ? null : para6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.del_flag
     *
     * @return the value of wpwx_schedule.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.del_flag
     *
     * @param delFlag the value for wpwx_schedule.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.created_time
     *
     * @return the value of wpwx_schedule.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.created_time
     *
     * @param createdTime the value for wpwx_schedule.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_schedule.updated_time
     *
     * @return the value of wpwx_schedule.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_schedule.updated_time
     *
     * @param updatedTime the value for wpwx_schedule.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}