package weixin.xigua.model;

import java.util.Date;

public class WpwxPublicArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.public_id
     *
     * @mbggenerated
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.article_id
     *
     * @mbggenerated
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public_article.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.id
     *
     * @return the value of wpwx_public_article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.id
     *
     * @param id the value for wpwx_public_article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.public_id
     *
     * @return the value of wpwx_public_article.public_id
     *
     * @mbggenerated
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.public_id
     *
     * @param publicId the value for wpwx_public_article.public_id
     *
     * @mbggenerated
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.article_id
     *
     * @return the value of wpwx_public_article.article_id
     *
     * @mbggenerated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.article_id
     *
     * @param articleId the value for wpwx_public_article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.type
     *
     * @return the value of wpwx_public_article.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.type
     *
     * @param type the value for wpwx_public_article.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.del_flag
     *
     * @return the value of wpwx_public_article.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.del_flag
     *
     * @param delFlag the value for wpwx_public_article.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.created_time
     *
     * @return the value of wpwx_public_article.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.created_time
     *
     * @param createdTime the value for wpwx_public_article.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public_article.updated_time
     *
     * @return the value of wpwx_public_article.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public_article.updated_time
     *
     * @param updatedTime the value for wpwx_public_article.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}