package weixin.xigua.model;

import java.util.Date;

public class WpwxPublic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.component_gzh_id
     *
     * @mbggenerated
     */
    private Integer componentGzhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.xigua_gzh_id
     *
     * @mbggenerated
     */
    private Integer xiguaGzhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.sogou_id
     *
     * @mbggenerated
     */
    private String sogouId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.alias
     *
     * @mbggenerated
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.category_id
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.qrcode_url
     *
     * @mbggenerated
     */
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.fans
     *
     * @mbggenerated
     */
    private Integer fans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.estimate_fans
     *
     * @mbggenerated
     */
    private Integer estimateFans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_public.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.id
     *
     * @return the value of wpwx_public.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.id
     *
     * @param id the value for wpwx_public.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.component_gzh_id
     *
     * @return the value of wpwx_public.component_gzh_id
     *
     * @mbggenerated
     */
    public Integer getComponentGzhId() {
        return componentGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.component_gzh_id
     *
     * @param componentGzhId the value for wpwx_public.component_gzh_id
     *
     * @mbggenerated
     */
    public void setComponentGzhId(Integer componentGzhId) {
        this.componentGzhId = componentGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.xigua_gzh_id
     *
     * @return the value of wpwx_public.xigua_gzh_id
     *
     * @mbggenerated
     */
    public Integer getXiguaGzhId() {
        return xiguaGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.xigua_gzh_id
     *
     * @param xiguaGzhId the value for wpwx_public.xigua_gzh_id
     *
     * @mbggenerated
     */
    public void setXiguaGzhId(Integer xiguaGzhId) {
        this.xiguaGzhId = xiguaGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.sogou_id
     *
     * @return the value of wpwx_public.sogou_id
     *
     * @mbggenerated
     */
    public String getSogouId() {
        return sogouId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.sogou_id
     *
     * @param sogouId the value for wpwx_public.sogou_id
     *
     * @mbggenerated
     */
    public void setSogouId(String sogouId) {
        this.sogouId = sogouId == null ? null : sogouId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.alias
     *
     * @return the value of wpwx_public.alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.alias
     *
     * @param alias the value for wpwx_public.alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.name
     *
     * @return the value of wpwx_public.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.name
     *
     * @param name the value for wpwx_public.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.head_img
     *
     * @return the value of wpwx_public.head_img
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.head_img
     *
     * @param headImg the value for wpwx_public.head_img
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.category_id
     *
     * @return the value of wpwx_public.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.category_id
     *
     * @param categoryId the value for wpwx_public.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.qrcode_url
     *
     * @return the value of wpwx_public.qrcode_url
     *
     * @mbggenerated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.qrcode_url
     *
     * @param qrcodeUrl the value for wpwx_public.qrcode_url
     *
     * @mbggenerated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.fans
     *
     * @return the value of wpwx_public.fans
     *
     * @mbggenerated
     */
    public Integer getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.fans
     *
     * @param fans the value for wpwx_public.fans
     *
     * @mbggenerated
     */
    public void setFans(Integer fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.estimate_fans
     *
     * @return the value of wpwx_public.estimate_fans
     *
     * @mbggenerated
     */
    public Integer getEstimateFans() {
        return estimateFans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.estimate_fans
     *
     * @param estimateFans the value for wpwx_public.estimate_fans
     *
     * @mbggenerated
     */
    public void setEstimateFans(Integer estimateFans) {
        this.estimateFans = estimateFans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.weight
     *
     * @return the value of wpwx_public.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.weight
     *
     * @param weight the value for wpwx_public.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.created_time
     *
     * @return the value of wpwx_public.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.created_time
     *
     * @param createdTime the value for wpwx_public.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.updated_time
     *
     * @return the value of wpwx_public.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.updated_time
     *
     * @param updatedTime the value for wpwx_public.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.del_flag
     *
     * @return the value of wpwx_public.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.del_flag
     *
     * @param delFlag the value for wpwx_public.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_public.introduction
     *
     * @return the value of wpwx_public.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_public.introduction
     *
     * @param introduction the value for wpwx_public.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}