package weixin.xigua.model;

import java.util.Date;

public class WpwxMaterial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.public_id
     *
     * @mbggenerated
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.material_sync_id
     *
     * @mbggenerated
     */
    private Integer materialSyncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.sequence_id
     *
     * @mbggenerated
     */
    private Integer sequenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.origin_article_id
     *
     * @mbggenerated
     */
    private Integer originArticleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.thumb_media_id
     *
     * @mbggenerated
     */
    private String thumbMediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.thumbnail
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.digest
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.show_cover_pic
     *
     * @mbggenerated
     */
    private Integer showCoverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.content_source_url
     *
     * @mbggenerated
     */
    private String contentSourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.id
     *
     * @return the value of wpwx_material.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.id
     *
     * @param id the value for wpwx_material.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.public_id
     *
     * @return the value of wpwx_material.public_id
     *
     * @mbggenerated
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.public_id
     *
     * @param publicId the value for wpwx_material.public_id
     *
     * @mbggenerated
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.material_sync_id
     *
     * @return the value of wpwx_material.material_sync_id
     *
     * @mbggenerated
     */
    public Integer getMaterialSyncId() {
        return materialSyncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.material_sync_id
     *
     * @param materialSyncId the value for wpwx_material.material_sync_id
     *
     * @mbggenerated
     */
    public void setMaterialSyncId(Integer materialSyncId) {
        this.materialSyncId = materialSyncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.sequence_id
     *
     * @return the value of wpwx_material.sequence_id
     *
     * @mbggenerated
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.sequence_id
     *
     * @param sequenceId the value for wpwx_material.sequence_id
     *
     * @mbggenerated
     */
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.origin_article_id
     *
     * @return the value of wpwx_material.origin_article_id
     *
     * @mbggenerated
     */
    public Integer getOriginArticleId() {
        return originArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.origin_article_id
     *
     * @param originArticleId the value for wpwx_material.origin_article_id
     *
     * @mbggenerated
     */
    public void setOriginArticleId(Integer originArticleId) {
        this.originArticleId = originArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.link
     *
     * @return the value of wpwx_material.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.link
     *
     * @param link the value for wpwx_material.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.title
     *
     * @return the value of wpwx_material.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.title
     *
     * @param title the value for wpwx_material.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.thumb_media_id
     *
     * @return the value of wpwx_material.thumb_media_id
     *
     * @mbggenerated
     */
    public String getThumbMediaId() {
        return thumbMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.thumb_media_id
     *
     * @param thumbMediaId the value for wpwx_material.thumb_media_id
     *
     * @mbggenerated
     */
    public void setThumbMediaId(String thumbMediaId) {
        this.thumbMediaId = thumbMediaId == null ? null : thumbMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.thumbnail
     *
     * @return the value of wpwx_material.thumbnail
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.thumbnail
     *
     * @param thumbnail the value for wpwx_material.thumbnail
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.author
     *
     * @return the value of wpwx_material.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.author
     *
     * @param author the value for wpwx_material.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.digest
     *
     * @return the value of wpwx_material.digest
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.digest
     *
     * @param digest the value for wpwx_material.digest
     *
     * @mbggenerated
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.show_cover_pic
     *
     * @return the value of wpwx_material.show_cover_pic
     *
     * @mbggenerated
     */
    public Integer getShowCoverPic() {
        return showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.show_cover_pic
     *
     * @param showCoverPic the value for wpwx_material.show_cover_pic
     *
     * @mbggenerated
     */
    public void setShowCoverPic(Integer showCoverPic) {
        this.showCoverPic = showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.content_source_url
     *
     * @return the value of wpwx_material.content_source_url
     *
     * @mbggenerated
     */
    public String getContentSourceUrl() {
        return contentSourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.content_source_url
     *
     * @param contentSourceUrl the value for wpwx_material.content_source_url
     *
     * @mbggenerated
     */
    public void setContentSourceUrl(String contentSourceUrl) {
        this.contentSourceUrl = contentSourceUrl == null ? null : contentSourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.del_flag
     *
     * @return the value of wpwx_material.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.del_flag
     *
     * @param delFlag the value for wpwx_material.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.created_time
     *
     * @return the value of wpwx_material.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.created_time
     *
     * @param createdTime the value for wpwx_material.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.updated_time
     *
     * @return the value of wpwx_material.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.updated_time
     *
     * @param updatedTime the value for wpwx_material.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material.content
     *
     * @return the value of wpwx_material.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material.content
     *
     * @param content the value for wpwx_material.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}