package weixin.xigua.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WpwxMaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public WpwxMaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("WPWX_MATERIAL.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPublicIdIsNull() {
            addCriterion("WPWX_MATERIAL.public_id is null");
            return (Criteria) this;
        }

        public Criteria andPublicIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.public_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublicIdEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id =", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id <>", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id >", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id >=", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id <", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.public_id <=", value, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.public_id in", values, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.public_id not in", values, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.public_id between", value1, value2, "publicId");
            return (Criteria) this;
        }

        public Criteria andPublicIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.public_id not between", value1, value2, "publicId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdIsNull() {
            addCriterion("WPWX_MATERIAL.material_sync_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.material_sync_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id =", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id <>", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id >", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id >=", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id <", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.material_sync_id <=", value, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.material_sync_id in", values, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.material_sync_id not in", values, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.material_sync_id between", value1, value2, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andMaterialSyncIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.material_sync_id not between", value1, value2, "materialSyncId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNull() {
            addCriterion("WPWX_MATERIAL.sequence_id is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.sequence_id is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id =", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id <>", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id >", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id >=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id <", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.sequence_id <=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.sequence_id in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.sequence_id not in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.sequence_id between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.sequence_id not between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdIsNull() {
            addCriterion("WPWX_MATERIAL.origin_article_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.origin_article_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id =", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id <>", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id >", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id >=", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id <", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.origin_article_id <=", value, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.origin_article_id in", values, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.origin_article_id not in", values, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.origin_article_id between", value1, value2, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andOriginArticleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.origin_article_id not between", value1, value2, "originArticleId");
            return (Criteria) this;
        }

        public Criteria andLinkIsNull() {
            addCriterion("WPWX_MATERIAL.link is null");
            return (Criteria) this;
        }

        public Criteria andLinkIsNotNull() {
            addCriterion("WPWX_MATERIAL.link is not null");
            return (Criteria) this;
        }

        public Criteria andLinkEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.link =", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.link <>", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.link >", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.link >=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThan(String value) {
            addCriterion("WPWX_MATERIAL.link <", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.link <=", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkLike(String value) {
            addCriterion("WPWX_MATERIAL.link like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotLike(String value) {
            addCriterion("WPWX_MATERIAL.link not like", value, "link");
            return (Criteria) this;
        }

        public Criteria andLinkIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.link in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.link not in", values, "link");
            return (Criteria) this;
        }

        public Criteria andLinkBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.link between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andLinkNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.link not between", value1, value2, "link");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("WPWX_MATERIAL.title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("WPWX_MATERIAL.title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("WPWX_MATERIAL.title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("WPWX_MATERIAL.title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("WPWX_MATERIAL.title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdIsNull() {
            addCriterion("WPWX_MATERIAL.thumb_media_id is null");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdIsNotNull() {
            addCriterion("WPWX_MATERIAL.thumb_media_id is not null");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id =", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id <>", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id >", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id >=", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdLessThan(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id <", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id <=", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdLike(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id like", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdNotLike(String value) {
            addCriterion("WPWX_MATERIAL.thumb_media_id not like", value, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.thumb_media_id in", values, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.thumb_media_id not in", values, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.thumb_media_id between", value1, value2, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbMediaIdNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.thumb_media_id not between", value1, value2, "thumbMediaId");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNull() {
            addCriterion("WPWX_MATERIAL.thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNotNull() {
            addCriterion("WPWX_MATERIAL.thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail =", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail <>", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail >", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail >=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThan(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail <", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail <=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLike(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotLike(String value) {
            addCriterion("WPWX_MATERIAL.thumbnail not like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.thumbnail in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.thumbnail not in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.thumbnail between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.thumbnail not between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("WPWX_MATERIAL.author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("WPWX_MATERIAL.author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("WPWX_MATERIAL.author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("WPWX_MATERIAL.author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("WPWX_MATERIAL.author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andDigestIsNull() {
            addCriterion("WPWX_MATERIAL.digest is null");
            return (Criteria) this;
        }

        public Criteria andDigestIsNotNull() {
            addCriterion("WPWX_MATERIAL.digest is not null");
            return (Criteria) this;
        }

        public Criteria andDigestEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.digest =", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.digest <>", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.digest >", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.digest >=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThan(String value) {
            addCriterion("WPWX_MATERIAL.digest <", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.digest <=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLike(String value) {
            addCriterion("WPWX_MATERIAL.digest like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotLike(String value) {
            addCriterion("WPWX_MATERIAL.digest not like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.digest in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.digest not in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.digest between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.digest not between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIsNull() {
            addCriterion("WPWX_MATERIAL.show_cover_pic is null");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIsNotNull() {
            addCriterion("WPWX_MATERIAL.show_cover_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic =", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic <>", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic >", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic >=", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic <", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.show_cover_pic <=", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.show_cover_pic in", values, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.show_cover_pic not in", values, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.show_cover_pic between", value1, value2, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.show_cover_pic not between", value1, value2, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlIsNull() {
            addCriterion("WPWX_MATERIAL.content_source_url is null");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlIsNotNull() {
            addCriterion("WPWX_MATERIAL.content_source_url is not null");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url =", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlNotEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url <>", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlGreaterThan(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url >", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url >=", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlLessThan(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url <", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlLessThanOrEqualTo(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url <=", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlLike(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url like", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlNotLike(String value) {
            addCriterion("WPWX_MATERIAL.content_source_url not like", value, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.content_source_url in", values, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlNotIn(List<String> values) {
            addCriterion("WPWX_MATERIAL.content_source_url not in", values, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.content_source_url between", value1, value2, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andContentSourceUrlNotBetween(String value1, String value2) {
            addCriterion("WPWX_MATERIAL.content_source_url not between", value1, value2, "contentSourceUrl");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("WPWX_MATERIAL.del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("WPWX_MATERIAL.del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_MATERIAL.del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("WPWX_MATERIAL.del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_MATERIAL.del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("WPWX_MATERIAL.created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("WPWX_MATERIAL.created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("WPWX_MATERIAL.created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("WPWX_MATERIAL.created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("WPWX_MATERIAL.created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("WPWX_MATERIAL.created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("WPWX_MATERIAL.created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("WPWX_MATERIAL.created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("WPWX_MATERIAL.updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("WPWX_MATERIAL.updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("WPWX_MATERIAL.updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("WPWX_MATERIAL.updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("WPWX_MATERIAL.updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("WPWX_MATERIAL.updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("WPWX_MATERIAL.updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_material
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}