package weixin.xigua.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WpwxPublicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public WpwxPublicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("WPWX_PUBLIC.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("WPWX_PUBLIC.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdIsNull() {
            addCriterion("WPWX_PUBLIC.component_gzh_id is null");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdIsNotNull() {
            addCriterion("WPWX_PUBLIC.component_gzh_id is not null");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id =", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id <>", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id >", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id >=", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id <", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.component_gzh_id <=", value, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.component_gzh_id in", values, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.component_gzh_id not in", values, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.component_gzh_id between", value1, value2, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andComponentGzhIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.component_gzh_id not between", value1, value2, "componentGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdIsNull() {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id is null");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdIsNotNull() {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id is not null");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id =", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id <>", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id >", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id >=", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id <", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id <=", value, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id in", values, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id not in", values, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id between", value1, value2, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andXiguaGzhIdNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.xigua_gzh_id not between", value1, value2, "xiguaGzhId");
            return (Criteria) this;
        }

        public Criteria andSogouIdIsNull() {
            addCriterion("WPWX_PUBLIC.sogou_id is null");
            return (Criteria) this;
        }

        public Criteria andSogouIdIsNotNull() {
            addCriterion("WPWX_PUBLIC.sogou_id is not null");
            return (Criteria) this;
        }

        public Criteria andSogouIdEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id =", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id <>", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id >", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id >=", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdLessThan(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id <", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id <=", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdLike(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id like", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdNotLike(String value) {
            addCriterion("WPWX_PUBLIC.sogou_id not like", value, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.sogou_id in", values, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.sogou_id not in", values, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.sogou_id between", value1, value2, "sogouId");
            return (Criteria) this;
        }

        public Criteria andSogouIdNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.sogou_id not between", value1, value2, "sogouId");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("WPWX_PUBLIC.alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("WPWX_PUBLIC.alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("WPWX_PUBLIC.alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("WPWX_PUBLIC.alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("WPWX_PUBLIC.alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("WPWX_PUBLIC.name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("WPWX_PUBLIC.name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("WPWX_PUBLIC.name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("WPWX_PUBLIC.name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("WPWX_PUBLIC.name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andHeadImgIsNull() {
            addCriterion("WPWX_PUBLIC.head_img is null");
            return (Criteria) this;
        }

        public Criteria andHeadImgIsNotNull() {
            addCriterion("WPWX_PUBLIC.head_img is not null");
            return (Criteria) this;
        }

        public Criteria andHeadImgEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.head_img =", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.head_img <>", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.head_img >", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.head_img >=", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgLessThan(String value) {
            addCriterion("WPWX_PUBLIC.head_img <", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.head_img <=", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgLike(String value) {
            addCriterion("WPWX_PUBLIC.head_img like", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgNotLike(String value) {
            addCriterion("WPWX_PUBLIC.head_img not like", value, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.head_img in", values, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.head_img not in", values, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.head_img between", value1, value2, "headImg");
            return (Criteria) this;
        }

        public Criteria andHeadImgNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.head_img not between", value1, value2, "headImg");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("WPWX_PUBLIC.category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("WPWX_PUBLIC.category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(String value) {
            addCriterion("WPWX_PUBLIC.category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLike(String value) {
            addCriterion("WPWX_PUBLIC.category_id like", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotLike(String value) {
            addCriterion("WPWX_PUBLIC.category_id not like", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIsNull() {
            addCriterion("WPWX_PUBLIC.qrcode_url is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIsNotNull() {
            addCriterion("WPWX_PUBLIC.qrcode_url is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url =", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url <>", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlGreaterThan(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url >", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url >=", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLessThan(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url <", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLessThanOrEqualTo(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url <=", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLike(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url like", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotLike(String value) {
            addCriterion("WPWX_PUBLIC.qrcode_url not like", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.qrcode_url in", values, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotIn(List<String> values) {
            addCriterion("WPWX_PUBLIC.qrcode_url not in", values, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.qrcode_url between", value1, value2, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotBetween(String value1, String value2) {
            addCriterion("WPWX_PUBLIC.qrcode_url not between", value1, value2, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andFansIsNull() {
            addCriterion("WPWX_PUBLIC.fans is null");
            return (Criteria) this;
        }

        public Criteria andFansIsNotNull() {
            addCriterion("WPWX_PUBLIC.fans is not null");
            return (Criteria) this;
        }

        public Criteria andFansEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.fans =", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.fans <>", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.fans >", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.fans >=", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.fans <", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.fans <=", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.fans in", values, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.fans not in", values, "fans");
            return (Criteria) this;
        }

        public Criteria andFansBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.fans between", value1, value2, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.fans not between", value1, value2, "fans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansIsNull() {
            addCriterion("WPWX_PUBLIC.estimate_fans is null");
            return (Criteria) this;
        }

        public Criteria andEstimateFansIsNotNull() {
            addCriterion("WPWX_PUBLIC.estimate_fans is not null");
            return (Criteria) this;
        }

        public Criteria andEstimateFansEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans =", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans <>", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans >", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans >=", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans <", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.estimate_fans <=", value, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.estimate_fans in", values, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.estimate_fans not in", values, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.estimate_fans between", value1, value2, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andEstimateFansNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.estimate_fans not between", value1, value2, "estimateFans");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WPWX_PUBLIC.weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WPWX_PUBLIC.weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("WPWX_PUBLIC.created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("WPWX_PUBLIC.created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("WPWX_PUBLIC.created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("WPWX_PUBLIC.created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("WPWX_PUBLIC.created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("WPWX_PUBLIC.created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("WPWX_PUBLIC.created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("WPWX_PUBLIC.created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("WPWX_PUBLIC.updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("WPWX_PUBLIC.updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("WPWX_PUBLIC.updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("WPWX_PUBLIC.updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("WPWX_PUBLIC.updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("WPWX_PUBLIC.updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("WPWX_PUBLIC.updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("WPWX_PUBLIC.del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("WPWX_PUBLIC.del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("WPWX_PUBLIC.del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("WPWX_PUBLIC.del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("WPWX_PUBLIC.del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_public
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}