package weixin.xigua.model;

import java.util.Date;

public class WpwxMaterialSync {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.public_id
     *
     * @mbggenerated
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.media_id
     *
     * @mbggenerated
     */
    private String mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.schedule_time
     *
     * @mbggenerated
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_material_sync.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.id
     *
     * @return the value of wpwx_material_sync.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.id
     *
     * @param id the value for wpwx_material_sync.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.user_id
     *
     * @return the value of wpwx_material_sync.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.user_id
     *
     * @param userId the value for wpwx_material_sync.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.public_id
     *
     * @return the value of wpwx_material_sync.public_id
     *
     * @mbggenerated
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.public_id
     *
     * @param publicId the value for wpwx_material_sync.public_id
     *
     * @mbggenerated
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.media_id
     *
     * @return the value of wpwx_material_sync.media_id
     *
     * @mbggenerated
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.media_id
     *
     * @param mediaId the value for wpwx_material_sync.media_id
     *
     * @mbggenerated
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId == null ? null : mediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.schedule_time
     *
     * @return the value of wpwx_material_sync.schedule_time
     *
     * @mbggenerated
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.schedule_time
     *
     * @param scheduleTime the value for wpwx_material_sync.schedule_time
     *
     * @mbggenerated
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.send_time
     *
     * @return the value of wpwx_material_sync.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.send_time
     *
     * @param sendTime the value for wpwx_material_sync.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.status
     *
     * @return the value of wpwx_material_sync.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.status
     *
     * @param status the value for wpwx_material_sync.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.created_time
     *
     * @return the value of wpwx_material_sync.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.created_time
     *
     * @param createdTime the value for wpwx_material_sync.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.updated_time
     *
     * @return the value of wpwx_material_sync.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.updated_time
     *
     * @param updatedTime the value for wpwx_material_sync.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_material_sync.del_flag
     *
     * @return the value of wpwx_material_sync.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_material_sync.del_flag
     *
     * @param delFlag the value for wpwx_material_sync.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}