package weixin.xigua.model;

import java.util.Date;

public class WpwxMass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.material_sync_id
     *
     * @mbggenerated
     */
    private Integer materialSyncId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.send_time
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.schedule_time
     *
     * @mbggenerated
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.is_to_all
     *
     * @mbggenerated
     */
    private Integer isToAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.msgtype
     *
     * @mbggenerated
     */
    private String msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.thumb_media_id
     *
     * @mbggenerated
     */
    private String thumbMediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.msg_id
     *
     * @mbggenerated
     */
    private Integer msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.msg_data_id
     *
     * @mbggenerated
     */
    private Integer msgDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wpwx_mass.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.id
     *
     * @return the value of wpwx_mass.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.id
     *
     * @param id the value for wpwx_mass.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.material_sync_id
     *
     * @return the value of wpwx_mass.material_sync_id
     *
     * @mbggenerated
     */
    public Integer getMaterialSyncId() {
        return materialSyncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.material_sync_id
     *
     * @param materialSyncId the value for wpwx_mass.material_sync_id
     *
     * @mbggenerated
     */
    public void setMaterialSyncId(Integer materialSyncId) {
        this.materialSyncId = materialSyncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.send_time
     *
     * @return the value of wpwx_mass.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.send_time
     *
     * @param sendTime the value for wpwx_mass.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.schedule_time
     *
     * @return the value of wpwx_mass.schedule_time
     *
     * @mbggenerated
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.schedule_time
     *
     * @param scheduleTime the value for wpwx_mass.schedule_time
     *
     * @mbggenerated
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.is_to_all
     *
     * @return the value of wpwx_mass.is_to_all
     *
     * @mbggenerated
     */
    public Integer getIsToAll() {
        return isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.is_to_all
     *
     * @param isToAll the value for wpwx_mass.is_to_all
     *
     * @mbggenerated
     */
    public void setIsToAll(Integer isToAll) {
        this.isToAll = isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.group_id
     *
     * @return the value of wpwx_mass.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.group_id
     *
     * @param groupId the value for wpwx_mass.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.msgtype
     *
     * @return the value of wpwx_mass.msgtype
     *
     * @mbggenerated
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.msgtype
     *
     * @param msgtype the value for wpwx_mass.msgtype
     *
     * @mbggenerated
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype == null ? null : msgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.title
     *
     * @return the value of wpwx_mass.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.title
     *
     * @param title the value for wpwx_mass.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.description
     *
     * @return the value of wpwx_mass.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.description
     *
     * @param description the value for wpwx_mass.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.thumb_media_id
     *
     * @return the value of wpwx_mass.thumb_media_id
     *
     * @mbggenerated
     */
    public String getThumbMediaId() {
        return thumbMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.thumb_media_id
     *
     * @param thumbMediaId the value for wpwx_mass.thumb_media_id
     *
     * @mbggenerated
     */
    public void setThumbMediaId(String thumbMediaId) {
        this.thumbMediaId = thumbMediaId == null ? null : thumbMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.msg_id
     *
     * @return the value of wpwx_mass.msg_id
     *
     * @mbggenerated
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.msg_id
     *
     * @param msgId the value for wpwx_mass.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.msg_data_id
     *
     * @return the value of wpwx_mass.msg_data_id
     *
     * @mbggenerated
     */
    public Integer getMsgDataId() {
        return msgDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.msg_data_id
     *
     * @param msgDataId the value for wpwx_mass.msg_data_id
     *
     * @mbggenerated
     */
    public void setMsgDataId(Integer msgDataId) {
        this.msgDataId = msgDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.created_time
     *
     * @return the value of wpwx_mass.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.created_time
     *
     * @param createdTime the value for wpwx_mass.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.updated_time
     *
     * @return the value of wpwx_mass.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.updated_time
     *
     * @param updatedTime the value for wpwx_mass.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wpwx_mass.del_flag
     *
     * @return the value of wpwx_mass.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wpwx_mass.del_flag
     *
     * @param delFlag the value for wpwx_mass.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}