package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxUser;
import weixin.xigua.model.WpwxUserExample;

public interface WpwxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int countByExample(WpwxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int insert(WpwxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int insertSelective(WpwxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    List<WpwxUser> selectByExample(WpwxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    WpwxUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxUser record, @Param("example") WpwxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxUser record, @Param("example") WpwxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxUser record);
}