package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxUserArticle;
import weixin.xigua.model.WpwxUserArticleExample;

public interface WpwxUserArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int countByExample(WpwxUserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxUserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int insert(WpwxUserArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int insertSelective(WpwxUserArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    List<WpwxUserArticle> selectByExample(WpwxUserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    WpwxUserArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxUserArticle record, @Param("example") WpwxUserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxUserArticle record, @Param("example") WpwxUserArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxUserArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxUserArticle record);
}