package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxMaterial;
import weixin.xigua.model.WpwxMaterialExample;

public interface WpwxMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int countByExample(WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int insert(WpwxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int insertSelective(WpwxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    List<WpwxMaterial> selectByExampleWithBLOBs(WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    List<WpwxMaterial> selectByExample(WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    WpwxMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxMaterial record, @Param("example") WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WpwxMaterial record, @Param("example") WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxMaterial record, @Param("example") WpwxMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WpwxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxMaterial record);
}