package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxArticleTemplate;
import weixin.xigua.model.WpwxArticleTemplateExample;

public interface WpwxArticleTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int countByExample(WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int insert(WpwxArticleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int insertSelective(WpwxArticleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    List<WpwxArticleTemplate> selectByExampleWithBLOBs(WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    List<WpwxArticleTemplate> selectByExample(WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    WpwxArticleTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxArticleTemplate record, @Param("example") WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WpwxArticleTemplate record, @Param("example") WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxArticleTemplate record, @Param("example") WpwxArticleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxArticleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WpwxArticleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxArticleTemplate record);
}