package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxArticleWidget;
import weixin.xigua.model.WpwxArticleWidgetExample;

public interface WpwxArticleWidgetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int countByExample(WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int insert(WpwxArticleWidget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int insertSelective(WpwxArticleWidget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    List<WpwxArticleWidget> selectByExampleWithBLOBs(WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    List<WpwxArticleWidget> selectByExample(WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    WpwxArticleWidget selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxArticleWidget record, @Param("example") WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WpwxArticleWidget record, @Param("example") WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxArticleWidget record, @Param("example") WpwxArticleWidgetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxArticleWidget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WpwxArticleWidget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_widget
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxArticleWidget record);
}