package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxMaterialSync;
import weixin.xigua.model.WpwxMaterialSyncExample;

public interface WpwxMaterialSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int countByExample(WpwxMaterialSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxMaterialSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int insert(WpwxMaterialSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int insertSelective(WpwxMaterialSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    List<WpwxMaterialSync> selectByExample(WpwxMaterialSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    WpwxMaterialSync selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxMaterialSync record, @Param("example") WpwxMaterialSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxMaterialSync record, @Param("example") WpwxMaterialSyncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxMaterialSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_material_sync
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxMaterialSync record);
}