package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxPublic;
import weixin.xigua.model.WpwxPublicExample;

public interface WpwxPublicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int countByExample(WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int insert(WpwxPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int insertSelective(WpwxPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    List<WpwxPublic> selectByExampleWithBLOBs(WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    List<WpwxPublic> selectByExample(WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    WpwxPublic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxPublic record, @Param("example") WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WpwxPublic record, @Param("example") WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxPublic record, @Param("example") WpwxPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WpwxPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxPublic record);
}