package weixin.xigua.dao;

import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxPublicArticle;
import weixin.xigua.model.WpwxPublicArticleAssociation;
import weixin.xigua.model.WpwxPublicArticleAssociationExample;
import weixin.xigua.model.WpwxPublicArticleExample;

import java.util.List;

public interface WpwxPublicArticleAssociationMapper {

    List<WpwxPublicArticleAssociation> selectAssociationByExample(WpwxPublicArticleAssociationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_public_article
     *
     * @mbggenerated
     */
    WpwxPublicArticleAssociation selectAssociationByPrimaryKey(Integer id);


}