package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxDict;
import weixin.xigua.model.WpwxDictExample;

public interface WpwxDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int countByExample(WpwxDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int insert(WpwxDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int insertSelective(WpwxDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    List<WpwxDict> selectByExample(WpwxDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    WpwxDict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxDict record, @Param("example") WpwxDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxDict record, @Param("example") WpwxDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxDict record);
}