package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxUserPublic;
import weixin.xigua.model.WpwxUserPublicExample;

public interface WpwxUserPublicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int countByExample(WpwxUserPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxUserPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int insert(WpwxUserPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int insertSelective(WpwxUserPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    List<WpwxUserPublic> selectByExample(WpwxUserPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    WpwxUserPublic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxUserPublic record, @Param("example") WpwxUserPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxUserPublic record, @Param("example") WpwxUserPublicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxUserPublic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxUserPublic record);
}