package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxMass;
import weixin.xigua.model.WpwxMassExample;

public interface WpwxMassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int countByExample(WpwxMassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxMassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int insert(WpwxMass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int insertSelective(WpwxMass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    List<WpwxMass> selectByExample(WpwxMassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxMass record, @Param("example") WpwxMassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_mass
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxMass record, @Param("example") WpwxMassExample example);
}