package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxArticleContent;
import weixin.xigua.model.WpwxArticleContentExample;

public interface WpwxArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int countByExample(WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int insert(WpwxArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int insertSelective(WpwxArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    List<WpwxArticleContent> selectByExampleWithBLOBs(WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    List<WpwxArticleContent> selectByExample(WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    WpwxArticleContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxArticleContent record, @Param("example") WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") WpwxArticleContent record, @Param("example") WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxArticleContent record, @Param("example") WpwxArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WpwxArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxArticleContent record);
}