package weixin.xigua.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.xigua.model.WpwxUserPublicStatus;
import weixin.xigua.model.WpwxUserPublicStatusExample;

public interface WpwxUserPublicStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int countByExample(WpwxUserPublicStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int deleteByExample(WpwxUserPublicStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int insert(WpwxUserPublicStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int insertSelective(WpwxUserPublicStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    List<WpwxUserPublicStatus> selectByExample(WpwxUserPublicStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    WpwxUserPublicStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WpwxUserPublicStatus record, @Param("example") WpwxUserPublicStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WpwxUserPublicStatus record, @Param("example") WpwxUserPublicStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WpwxUserPublicStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wpwx_user_public_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WpwxUserPublicStatus record);
}